CREATE OR REPLACE FORCE VIEW DSS_APP.GLDSS_CNTRL_FL1GR_IFACE_V AS
SELECT  PERAKT
      , BOL
      , MSTR_ACCT_ID
      , SUM(BELOPP_BASE_CURRENCY_AMT)   BELOPP_BASE_CURRENCY_AMT
      , SUM(BELOPP_LOCAL_CURRENCY_AMT)  BELOPP_LOCAL_CURRENCY_AMT
FROM GLDSS_CNTRL_FL1GR_IFACE_V_1
GROUP BY PERAKT
       , BOL
       , MSTR_ACCT_ID;

